name: civicconnect_app
description: CivicConnect - Report civic issues (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.2.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.0
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  image_picker: ^1.0.7
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.2
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
